from selenium.webdriver.common.by import By


class LoginLocators:
    USERNAME = (By.XPATH,"/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[1]/div/div[2]/input")
    PASSWORD = (By.XPATH, "/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[2]/div/div[2]/input")
    LOGIN = (By.CSS_SELECTOR, "#app > div.orangehrm-login-layout > div > div.orangehrm-login-container > div > div.orangehrm-login-slot > div.orangehrm-login-form > form > div.oxd-form-actions.orangehrm-login-action > button")

class AdminPageLocators:
    ADMIN_JOB = (By.XPATH, "/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a")

class AdminUserManagementLocators:
    USER_MANAGEMENT = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.oxd-topbar-body-nav-tab.--parent.--visited > span")
    USERS = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[1]/ul/li")
    JOB = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span")
    JOB_TITLE = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(1)")
    JOB_DROP = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span")
    PAY_GRADES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[2]")
    JOB_DROPDOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span")
    EMPLOYMENT_STATUS = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(3)")
    JOB_DROP_DOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span")
    JOB_CATEGORIES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/ul/li[4]")
    JOB_DOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[2]/span")
    WORK_SHIFTS = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent.--visited > ul > li:nth-child(5)")
    ORGANISATION = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span")
    GENERAL_INFORMATION = (By.XPATH, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(1) > a")
    ORGANISATION_DROPDOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span")
    LOCATIONS = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(2)")
    ORGANISATION_DROP_DOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/span")
    STRUCTURES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/ul/li[3]")
    QUALIFICATIONS = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li:nth-child(4) > span")
    SKILLS = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[1]")
    QUALIFICATIONS_DROPDOWN = (By.CSS_SELECTOR,"#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li:nth-child(4) > span")
    EDUCATION = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(2)")
    QUALIFICATIONS_DROP_DOWN = (By.XPATH,"/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[4]/span")
    LICENSES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[3]")
    QUALIFICATIONS_DROP_DOWN_BUTTON = (By.CSS_SELECTOR,"#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li:nth-child(4) > span")
    LANGUAGES = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab.--parent > ul > li:nth-child(4)")
    QUALIFICATIONS_DROP_DOWN_PAGE = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li:nth-child(4) > span")
    MEMBERSHIPS = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[4]/ul/li[5]")
    NATIONALITIES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/a")
    CORPORATE_BRANDING = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab > ul > div:nth-child(2) > li > a")
    CONFIGURATION = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    EMAIL_CONFIGURATION = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[1]")
    CONFIGURATION_DROP = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    EMAIL_SUBSCRIPTIONS = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[2]")
    CONFIGURATION_DOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    LOCALIZATION = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[3]")
    CONFIGURATION_DROPDOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    LANGUAGE_PACKAGES = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[4]")
    CONFIGURATION_DROP_DOWN = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    MODULES = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab > ul > div:nth-child(3) > ul > li:nth-child(5)")
    CONFIGURATION_BUTTON = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    SOCIAL_MEDIA_AUTHENTICATION = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[7]/a")
    CONFIGURATION_PAGE = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    REGISTER_OAUTH_CLIENT = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[5]/ul/div[3]/ul/li[7]")
    CONFIGURATION_DROP_BUTTON = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[7]/span")
    LDAP_CONFIGURATION = (By.CSS_SELECTOR, "#app > div.oxd-layout.orangehrm-upgrade-layout > div.oxd-layout-navigation > header > div.oxd-topbar-body > nav > ul > li.--active.oxd-topbar-body-nav-tab > ul > div:nth-child(3) > ul > li:nth-child(8)")

class LogoutLocators:
    LOG_OUT = (By.XPATH, "/html/body/div/div[1]/div[1]/header/div[1]/div[3]/ul/li/ul/li[4]/a")